### ISSUE TITLE
Change procurement-ruby to use V2 consumers API

### ISSUE THREAD

**Issue by nickcampbell18** [zaikio/zaikio-procurement-ruby#23]

**Comment by nickcampbell18** [comment]
I'm ok with breaking change, to be honest - if you need 1.x you can keep using the last released version, but we aren't maintaining those v1 APIs anymore?

**Comment by mauricevogel** [comment]
There's another question over here after I had a brief look again.

Currently there's a config option `flavor` determining whether or not to hit the supplier or consumer side endpoints. Given this is only used by us so far and I doubt any supplier will ever use it, would you have any objections against removing this completely?

**Comment by nickcampbell18** [comment]
Procurement Connect uses the supplier mode 🤦  Let's do this: remove any existing consumer-only models, mark the rest as supplier models (maybe using a breaking change e.g. `Zaikio::Procurement::Variant` -> `Supplier::Variant`), and then build a fresh set of v2 models?
